### ISSUE TITLE
GPU code gives the wrong derivatives

### ISSUE THREAD

**Issue by lgarrison** [bd-j/forcepho#26]
The GPU code at the end of the MIT Hackathon runs fast but gives the wrong chi2 derivatives compared to the CPU (the chi value itself is quite close).  The CPU derivatives agree with the numerical derivatives.

The GPU code is in the `mithack` branch and a simple script to run a proposal and print the derivatives is here: https://github.com/bd-j/forcepho/blob/mithack/tests/run_patch_gpu_test_simple.py

**Comment by lgarrison** [comment]
This is fixed in `mithack`.  The main culprit was a bug in rewriting the math to avoid a division in `ComputeGaussianDerivative`; there was also a factor of -2 from ln(p) vs chi2 and catastrophic cancellation in the use of global float32 ra/dec.  The former two were quick fixes; for the latter, we've added a routine to re-center the coordinates in `patch_conversion.py` while still in float64.  Long term, we'll probably want to patch-center the coordinates instead of field-center.

The chi2 is now accurate to all decimal places; the chi2 derivs match to at least 4 decimal places.

**Comment by deisenstein** [comment]
Sounds like that division problem was my fault; sorry!  Glad you found the
bug(s).

Regarding the coordinates, we will need to be particularly careful about
this in the future when we change to half2.  My thinking there is to
express the Gaussian center in terms of a integer number of pixels plus a
fractional pixel, computed in float but then storing as half2.  Then we can
do dx = (xp-x_int)-x_frac, and xp-x_int will avoid round-off error.  We
need this even for patch-centered coords, since a patch may be 300 pixels
on a side and we want better than 0.1 pixel accuracy in the subtraction.
